CREATE DATABASE IF NOT EXISTS app_db;
GRANT ALL PRIVILEGES ON app_db.* TO 'root'@'%';

CREATE DATABASE IF NOT EXISTS log_db;
GRANT ALL PRIVILEGES ON log_db.* TO 'root'@'%';

CREATE DATABASE IF NOT EXISTS test_db;
GRANT ALL PRIVILEGES ON test_db.* TO 'root'@'%';

CREATE USER 'guest'@'%' IDENTIFIED WITH mysql_native_password BY 'guest';
GRANT ALL PRIVILEGES ON *.* TO 'guest'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'replica'@'%' IDENTIFIED WITH mysql_native_password BY 'replica';
GRANT REPLICATION SLAVE ON *.* TO 'replica'@'%';
FLUSH PRIVILEGES;
